call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'luochen1990/rainbow'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'fatih/vim-go'
Plug 'skywind3000/vim-rt-format', { 'do': 'pip3 install autopep8' }
Plug 'cespare/vim-toml'
call plug#end()

" general settings
syntax on
set nofoldenable
set nobackup
set expandtab
set ts=4
set sw=4
set sts=4
set nu
set laststatus=2

" enable rainbow by default
let g:rainbow_active = 1 

" use <tab> for trigger completion and navigate to the next complete item
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction

inoremap <silent><expr> <Tab>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<Tab>" :
      \ coc#refresh()

" coc config
set cmdheight=1
set updatetime=300
set shortmess+=c
set signcolumn=yes

colorscheme ron

autocmd BufWritePre *.go :silent call CocAction('runCommand', 'editor.action.organizeImport')

map <C-p> <ESC>:!clear && cargo run<CR>
